name: carpooling
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  shared_preferences: ^2.0.11
  flutter:
    sdk: flutter
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  google_maps_flutter: ^2.2.0
  provider: 6.1.2
  http: ^1.0.0
  image_picker: ^0.8.7+4

dev_dependencies:
  hive_generator: ^1.0.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/welcome_image.png
    - assets/welcome.png
    - assets/driver1.jpg
    - assets/driver2.jpg
    - assets/driver3.png
    - assets/driver4.png
    - assets/driver5.png
    - assets/driver6.png
    - assets/driver7.png
    - assets/driver8.png
    - assets/icons/car_icon.png

  uses-material-design: true
